# Generated by Django 2.2 on 2023-03-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_auto_20230327_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaldata',
            name='q1_v5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaldata',
            name='q2_v5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaldata',
            name='q3_v5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaldata',
            name='q4_v5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaldata',
            name='q5_v5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
