# Generated by Django 2.2 on 2023-07-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_auto_20230330_0204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvalData',
        ),
    ]
